task:
  name: Build (Alpine Linux)
  container:
    image: alpine:3.16
    cpu: 8
  environment:
    #RUSTFLAGS: "-C target-feature=-crt-static"
    PATH: "$HOME/.cargo/bin:$PATH"
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock
  install_script:
    - apk --update add curl git gcc musl-dev
    - curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal
  test_script:
    - cargo test
  before_cache_script: rm -rf $HOME/.cargo/registry/index
